### ISSUE TITLE
stb_image.h  security issue : heap-based buffer over-read in stbi__tga_load

### ISSUE THREAD

**Issue by stavBodik** [nothings/stb#1424]
Hi, I would like to know if there will be update for stb_image.h due to the security issue it has ?

Reference : 

https://vuldb.com/?id.212812

https://groups.google.com/g/linux.debian.bugs.dist/c/ijJm5r8SWyk

stb_image.h (aka the stb image loader) 2.23 has a heap-based buffer over-read in stbi__tga_load, leading to Information Disclosure or Denial of Service.

If yes, do we know when ?

**Comment by rygorous** [comment]
That's #1178.

That bug was fixed on the dev branch last year and the fix has since been merged to master, I don't know why the version number or issue weren't updated at the time, but unless you have a different repro from the one reported in that issue, it ought to be fixed.

**Comment by stavBodik** [comment]
Hi @rygorous and thanks for the reply ,

By looking at this : https://github.com/nothings/stb/issues/1307

I can see that line 1180 is still the same in the latest code version of 2.27,maybe the fix was for another similar issue ?

Can you please give me a link to the **merge request** were it was fixed ? the other fix that you have mentioned that is done in the last year ?

**Comment by rygorous** [comment]
That one's a completely different bug and not the one you linked (which was referring to #1178, at least by the linux.debian.bugs link).

https://github.com/nothings/stb/commit/5ba0baaa269b3fd681828e0e3b3ac0f1472eaf40 is where it was fixed in "dev", and it's been fast-forwarded onto master since so there's no merge commit.

**Comment by stavBodik** [comment]
@rygorous Thanks, will you prepare fix for 

https://github.com/nothings/stb/issues/1307

? If yes Can you say when?

**Comment by rygorous** [comment]
Sean and I are busy with other things and do all work on the stb libs in batches maybe once a year. We try to prioritize security issues when working on the libs but that doesn't magically make either of us have any more time or energy to spend on the stb libs than the maybe 3 weekends a year we've been averaging over the last 8 years. I'll try to get around to it within the next few weeks but I can't make any promises.

**Comment by rygorous** [comment]
Fix for this is merged into the dev branch, will be in the next release (hopefully soon).

**Comment by stavBodik** [comment]
> Fix for this is merged into the dev branch, will be in the next release (hopefully soon).

@rygorous 
Thanks you very much, we really appriciate this 🙏

**Comment by rygorous** [comment]
Fixed in 2.28.
